### ISSUE TITLE
Better docs for aurelia.json config of Rxjs v6

### ISSUE THREAD

**Issue by zewa666** [aurelia/store#43]
Need more docs for:

* Operator Imports
* Rxjs-compat

**Comment by alexisargyris** [comment]
Re-read the whole article. Only one sentence stood out:

"Since having access to the BehaviorSubject would allow consumers to directly emit the next value, instead of a front-facing state property, being an Observable which connects to the BehaviorSubject, is exposed."

Maybe it could be made a bit more clear?

BTW, the plugin works great!

**Comment by zewa666** [comment]
Yep I'll make sure to rephrase this better.

**Comment by zewa666** [comment]
@alexisargyris could you take a look at the [last commit](https://github.com/aurelia/store/commit/c0bbd5f5849770828f78f274ee6d8292bb684858). I hope this explains the intention better

**Comment by alexisargyris** [comment]
Most definitely! Thanks
